model: 
  model : ResNet18
  model_path : null
  device  : cuda
data:
  dataset : tfds
  dataset_name : cifar10
  positive_class : 7
train:
  optimizer : 
    name : SGD
    config : 
      lr : 0.02
  loss_fn : 
    name : CrossEntropyLoss
  batch_size : 128
  epochs : 25
active_learner:
  iterations : 30
  strategy : margin_based
  diversity_sampling : pick_top_n
  num_labeled : 1500
  limit : -1
  labeler : 
    method : autolabel
    positive_class : 7
  



